---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/todos":
    post:
      summary: Creates a todo
      tags:
      - Todos
      parameters: []
      responses:
        '201':
          description: success
        '422':
          description: unprocessable_entity
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/todo"
    get:
      summary: Retrieves a todo list
      tags:
      - Todos
      responses:
        '200':
          description: success
  "/api/v1/todos/{id}":
    get:
      summary: Retrieves a todo
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/todo"
        '404':
          description: not_found
    put:
      summary: Update todo by id
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: not_found
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/todo"
    delete:
      summary: Delete todo by id
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: no_content
        '404':
          description: not_found
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    todo:
      type: object
      properties:
        name:
          type: string
        done:
          type: boolean
      required:
      - name
      - done
    todos:
      type: array
      items:
        "$ref": "#/components/schemas/todo"
servers:
- url: http://localhost:3000
